server:
  port: 9000

logging:
  level:
    root: error
    #    org.springframework.web: DEBUG
    org.springframework.security: error
    org.springframework.security.oauth2: error

spring:
  datasource:
    username: root
    password: as212000
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flame?serverTimezone=Asia/Shanghai
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      # create: 程序启动时，创建数据库表，如果表已存在则删除后重新创建
      # create-drop: 程序启动时，创建数据库表，使用完毕后自动删除表
      # none: 功能关闭
      # update：程序启动时，如果没有实体类对应的表则创建。如果有则使用原来的表。
      # validate： 校验实体类和数据库表的映射关系，如果字段属性不能完全对应则抛出异常
    generate-ddl: true # 开发阶段开启逆向工程 根据数据库表生成实体
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect # 指定数据库平台(方言)
  redis:
    host: localhost
  data:
    neo4j:
      open-in-view: false