server:
  port: 8090
  servlet:
    session:
      cookie:
        name: admin # 防止多客户端情况下cookie冲突导致登录验证不通过

oauth2-server-url: http://localhost:9000

spring:
#  activiti:
#    database-schema-update: true
#    db-history-used: true
#    history-level: full
#    check-process-definitions: false

  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    sleuth:
      sampler:
        probability: 1.0 # 数据收集百分比
  application:
    name: admin
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.85.241:3306/flame
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

security:
  oauth2:
    client:
      client-id: client
      client-secret: 123
      user-authorization-uri: ${oauth2-server-url}/oauth/authorize
      access-token-uri: ${oauth2-server-url}/oauth/token
    resource:
      jwt:
        key-uri: ${oauth2-server-url}/oauth/token_key